services:
  # Python 네이티브 배포 서비스
  - name: cvfactory
    type: web
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn cvfactory.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --timeout 120
    envVars:
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: cvfactory.onrender.com,localhost,127.0.0.1
      - key: CSRF_TRUSTED_ORIGINS
        value: https://cvfactory.onrender.com,http://localhost:8000
      - key: CORS_ALLOWED_ORIGINS
        value: https://cvfactory.onrender.com,http://localhost:8000
      - key: RENDER
        value: true
      - key: RENDER_EXTERNAL_HOSTNAME
        value: cvfactory.onrender.com
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.9.21
      - key: DATABASE_URL
        fromDatabase:
          name: cvfactory-db
          property: connectionString
      - key: LOG_LEVEL
        value: DEBUG
      - key: API_KEY
        generateValue: true
      - key: GROQ_API_KEY
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        value: ""
      - key: GOOGLE_CLIENT_SECRET
        value: ""
      - key: SELENIUM_DRIVER_EXECUTABLE_PATH
        value: "/opt/render/project/usr/bin/chromedriver"
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /
    plan: free

databases:
  - name: cvfactory-db
    databaseName: cvfactory
    user: cvfactory
    plan: free 